### ISSUE TITLE
Immediate crash when trying to browse to pick my font.

### ISSUE THREAD

**Issue by Werdd** [SolarLune/masterplan#90]
Windows 10, compiled myself with a lot of help from my study buddy chatgpt. I see some error output but the console window closes too fast to read it.

**Comment by SolarLune** [comment]
If you want to see the error, you should be able to see it if you run MasterPlan from a command prompt (or run it with `go run .` from MasterPlan's source directory). If the problem is just when you actually select the font, it might be an issue with the font, like missing or mangled glyphs.

**Comment by Werdd** [comment]
ahh ok, here's the output. It just happens when I click the browse button, little select file window pops up but it then immediately crashes. `PS C:\> cd .\masterplan\
PS C:\masterplan> .\masterplan.exe
2023/04/06 14:48:48 Release mode: dev
2023/04/06 14:48:49 Speaker system initialized properly with sample rate 44100 and buffer size 512.
2023/04/06 14:48:50 MasterPlan initialized successfully.
2023/04/06 14:48:50 Load started.
2023/04/06 14:48:50 Recent files list updated...
2023/04/06 14:48:50 Any saved images loaded.
2023/04/06 14:48:50 Loading pages...
2023/04/06 14:48:50 Project loaded successfully.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x7ff7842ffc02]

goroutine 50 [running]:
main.loadThemes.func1({0xc00001c300, 0x24}, {0x0?, 0x0?}, {0x7ff7845b4f20, 0xc0000c9aa0})
        C:/masterplan/gui.go:102 +0x82
path/filepath.Walk({0xc00001c300, 0x24}, 0xc000573f68)
        C:/Program Files/Go/src/path/filepath/path.go:569 +0x50
main.loadThemes()
        C:/masterplan/gui.go:100 +0x8d
main.main.func2()
        C:/masterplan/main.go:297 +0x9c
created by main.main
        C:/masterplan/main.go:291 +0x112b
PS C:\masterplan>`
